config/routes.rb
SampleApp::Application.routes.draw do
    resources :users
    match '/signup',  :to => 'users#new'
    match 'contact' => 'pages#contact'
    match 'about' => 'pages#about'
    match 'help' => 'pages#help'
    match 'pages' => 'pages#home'

    root  :to => 'pages#home'
    
   
    

end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
	# password est un attribut virtuel 
	# attribut virtuel est un attribut qui ne correspond pas
	# à une colonne de la base de données et cela en utilsant
	# attr_accessor => password virtuel
	attr_accessor :password
   


	# Rendre les attributs nom et email accessibles
	attr_accessible :nom, :email, :password, 
	                 :password_confirmation
	
	validates :nom, :presence => true, :length => {:maximum =>50}
	email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, :presence     => true,
					   :format      => {:with => email_regex},
					   :uniqueness  => {:case_sensitive => false}

    validates :password, :presence    => true,
               :confirmation          => true,
               :length                => {:within =>6..40}
   before_save :encrypt_password

  def has_password?(password_soumis)
    encrypted_password == encrypt(password_soumis)
  end

  private

    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end



end


app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  #le controller Pages avec le titre suivant la page @titre

def index
  @titre ="Accueil"
end


  def home
  	@titre ="Accueil"
  end

  def contact
  	@titre ="Contact"
  end

  def about
  	@titre ="A propos"
  end
 
  def help
    @title ="Aide"
  end


end

app/controllers/users_controller.rb
# ------  Note ------------#
   # params : Contient des infos sur chaque requete





class UsersController < ApplicationController
  def new
  	#le titre personnalisé 
  	# pour la page de nouvel utilisateur
    @user =User.new
  	@titre ="Inscription"
  end
 
  def show 
     # trouver les utilisateurs avec leur id
  	 @user =User.find(params[:id])
     @titre =@user.nom
  end
  
  def index
  end

  def create
    @user =User.new(params[:user])
    if @user.save
      flash[:success] = "Bienvenue !" 
      redirect_to @user
      # traite un succés d'enregistrement
    else
      @titre="Inscription"
      render 'new'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	 def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag(user.email.downcase, :alt => user.nom,
                                            :class => 'gravatar',
                                            :gravatar => options)
  end
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "À Propos", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
      <li><a href="http://www.railstutorial.org/">Tutoriel Rails</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= image_tag("logo.png", :alt => "Application exemple", :class => "round") %>

  <nav class="round">
    <ul>
      <li><%= link_to "Accueil", root_path %></li>
      <li><%= link_to "Aide", help_path %></li>
      <li><%= link_to "Connexion", '#' %></li>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @titre %> </title>
  <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
</head>
<body>

<div class="container">
      
      <%= render 'layouts/header' %>
      <section class="round">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
      <!-- pour debugg -->
      <%= debug(params) if Rails.env.development? %>
    </div>

</body>
</html>

app/views/pages/about.html.erb
<h1>A propos de nous</h1>
<p>
	<a href="http://railstutorial.org/">Le Tutoriel Ruby on Rails</a> est un projet de livre et de screencasts pour apprendre le développement web avec <a href="http://rubyonrails.org/">Ruby on Rails</a>. Ceci est l'Application Exemple du tutoriel.


	

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>Contact Ruby on rails Tutoriel à propos de l'ApplicationExemple à <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a> Feedback page</p>

app/views/pages/help.html.erb
<h1>Aide</h1>
<p>Obtenez de l'aide sur le Tutoriel Ruby on Rails Tutorial sur la
  <a href="http://railstutorial.org/help">page d'aide du Tutoriel Rails</a>.
  Pour obtenir de l'aide sur cette application exemple, consultez le
  <a href="http://railstutorial.org/book">livre du Tutoriel Rails</a>.
</p>

app/views/pages/home.html.erb
	<h1>Home</h1>

<p>
  C'est la page d'accuile pour l'application exemple du
  <a href="http://railstutorial.org/">Tutoriel Ruby on Rails</a>.
</p>

<%= link_to "S'inscrire", signup_path , :class => "signup_button round" %>
	

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h5><%= pluralize(@user.errors.count, "erreur") %> 
        ont empêché d'enregistrer votre inscription</h5>
    <p>Merci de corriger ces champs :</p>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>  <%= msg %> </li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Inscription</h1>

<%= form_for(@user) do |f| %>
    <!-- Affiche les message d'erreur -->
<%= render 'shared/error_messages' %>
         <!-- en appelant le partiel /shared/error_messages -->
  <div class="field">
    <%= f.label :nom %><br />
    <%= f.text_field :nom %>
  </div>
  <div class="field">
  	<%= f.label :email%><br />
  	<%= f.text_field :email %>
  </div>
  <div class="field">
  	<%= f.label :password%><br />
  	<%= f.password_field :password %>
  </div>
  <div class="field">
  	<%= f.label :password_confirmation , "Confirmation"%><br />
  	<%= f.password_field :password_confirmation %>
  </div>
  <div class="action">
  	<%= f.submit "Inscription" %><br />	
  </div>

  
  
<% end %>

app/views/users/show.html.erb
<table class="profile" summary="Information profil">
  <tr>
    <td class="main">
      <h1>
        <!-- <%= gravatar_image_tag @user.email %> -->
        <%= @user.nom %>
      </h1>
    </td>
    <td class="sidebar round">
      <strong>Nom : </strong> <%= @user.nom %><br />
      <strong>URL :</strong>  <%= link_to user_path(@user), @user %>
    </td>
  </tr>
</table>
